name: Codestyle Checks
permissions:
  contents: read
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  check-codestyle:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    name: Check Codestyling
    steps:
      - uses: actions/checkout@v2

      - name: Check Codestyling
        run: source ./apps/ci/ci-codestyle.sh
